"""replace_audit_log_with_AuditEvent_projection

Revision ID: 4b8c069fdd6e
Revises: 5f8138ec81e5
Create Date: 2026-06-01 20:17:19.265082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b8c069fdd6e"
down_revision: str | Sequence[str] | None = "5f8138ec81e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditevent_projection",
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("action", sa.String(length=1), nullable=True),
        sa.Column("agent_username", sa.String(length=128), nullable=True),
        sa.Column("entity_reference", sa.String(length=256), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_auditevent_projection_action", "auditevent_projection", ["action"], unique=False
    )
    op.create_index(
        "ix_auditevent_projection_agent", "auditevent_projection", ["agent_username"], unique=False
    )
    op.create_index(
        "ix_auditevent_projection_entity",
        "auditevent_projection",
        ["entity_reference"],
        unique=False,
    )
    op.create_index(
        "ix_auditevent_projection_last_updated",
        "auditevent_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_auditevent_projection_recorded_at",
        "auditevent_projection",
        ["recorded_at"],
        unique=False,
    )
    op.drop_table("audit_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("resource_type", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("resource_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("actor", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("audit_log_pkey")),
    )
    op.drop_index("ix_auditevent_projection_recorded_at", table_name="auditevent_projection")
    op.drop_index("ix_auditevent_projection_last_updated", table_name="auditevent_projection")
    op.drop_index("ix_auditevent_projection_entity", table_name="auditevent_projection")
    op.drop_index("ix_auditevent_projection_agent", table_name="auditevent_projection")
    op.drop_index("ix_auditevent_projection_action", table_name="auditevent_projection")
    op.drop_table("auditevent_projection")
    # ### end Alembic commands ###
