"""extended_projection_tables

Revision ID: 5684b5d9f9f0
Revises: f5a6b7c8d9e0
Create Date: 2026-05-30 00:21:22.341947

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5684b5d9f9f0"
down_revision: str | Sequence[str] | None = "f5a6b7c8d9e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_appointment_projection_last_updated",
        "appointment_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_appointment_projection_patient",
        "appointment_projection",
        ["patient_reference"],
        unique=False,
    )
    op.create_index(
        "ix_appointment_projection_start_at", "appointment_projection", ["start_at"], unique=False
    )
    op.create_index(
        "ix_appointment_projection_status", "appointment_projection", ["status"], unique=False
    )
    op.create_table(
        "careplan_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("encounter_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_careplan_projection_encounter",
        "careplan_projection",
        ["encounter_reference"],
        unique=False,
    )
    op.create_index(
        "ix_careplan_projection_last_updated", "careplan_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_careplan_projection_status", "careplan_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_careplan_projection_subject", "careplan_projection", ["subject_reference"], unique=False
    )
    op.create_table(
        "claim_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_claim_projection_created_at", "claim_projection", ["created_at"], unique=False
    )
    op.create_index(
        "ix_claim_projection_last_updated", "claim_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_claim_projection_patient", "claim_projection", ["patient_reference"], unique=False
    )
    op.create_index("ix_claim_projection_status", "claim_projection", ["status"], unique=False)
    op.create_table(
        "communication_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_communication_projection_last_updated",
        "communication_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_communication_projection_sent_at", "communication_projection", ["sent_at"], unique=False
    )
    op.create_index(
        "ix_communication_projection_status", "communication_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_communication_projection_subject",
        "communication_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_table(
        "communicationrequest_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("authored_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_communicationrequest_projection_authored_on",
        "communicationrequest_projection",
        ["authored_on"],
        unique=False,
    )
    op.create_index(
        "ix_communicationrequest_projection_last_updated",
        "communicationrequest_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_communicationrequest_projection_status",
        "communicationrequest_projection",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_communicationrequest_projection_subject",
        "communicationrequest_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_table(
        "composition_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("encounter_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("type_code", sa.String(length=64), nullable=True),
        sa.Column("doc_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_composition_projection_doc_date", "composition_projection", ["doc_date"], unique=False
    )
    op.create_index(
        "ix_composition_projection_encounter",
        "composition_projection",
        ["encounter_reference"],
        unique=False,
    )
    op.create_index(
        "ix_composition_projection_last_updated",
        "composition_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_composition_projection_status", "composition_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_composition_projection_subject",
        "composition_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_index(
        "ix_composition_projection_type", "composition_projection", ["type_code"], unique=False
    )
    op.create_table(
        "coverage_projection",
        sa.Column("beneficiary_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_coverage_projection_beneficiary",
        "coverage_projection",
        ["beneficiary_reference"],
        unique=False,
    )
    op.create_index(
        "ix_coverage_projection_last_updated", "coverage_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_coverage_projection_status", "coverage_projection", ["status"], unique=False
    )
    op.create_table(
        "documentreference_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("doc_status", sa.String(length=32), nullable=True),
        sa.Column("type_code", sa.String(length=64), nullable=True),
        sa.Column("doc_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_documentreference_projection_doc_date",
        "documentreference_projection",
        ["doc_date"],
        unique=False,
    )
    op.create_index(
        "ix_documentreference_projection_doc_status",
        "documentreference_projection",
        ["doc_status"],
        unique=False,
    )
    op.create_index(
        "ix_documentreference_projection_last_updated",
        "documentreference_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_documentreference_projection_status",
        "documentreference_projection",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_documentreference_projection_subject",
        "documentreference_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_index(
        "ix_documentreference_projection_type",
        "documentreference_projection",
        ["type_code"],
        unique=False,
    )
    op.create_table(
        "episodeofcare_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_episodeofcare_projection_last_updated",
        "episodeofcare_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_episodeofcare_projection_patient",
        "episodeofcare_projection",
        ["patient_reference"],
        unique=False,
    )
    op.create_index(
        "ix_episodeofcare_projection_period_start",
        "episodeofcare_projection",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        "ix_episodeofcare_projection_status", "episodeofcare_projection", ["status"], unique=False
    )
    op.create_table(
        "familymemberhistory_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("relationship_code", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_familymemberhistory_projection_last_updated",
        "familymemberhistory_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_familymemberhistory_projection_patient",
        "familymemberhistory_projection",
        ["patient_reference"],
        unique=False,
    )
    op.create_index(
        "ix_familymemberhistory_projection_relationship",
        "familymemberhistory_projection",
        ["relationship_code"],
        unique=False,
    )
    op.create_index(
        "ix_familymemberhistory_projection_status",
        "familymemberhistory_projection",
        ["status"],
        unique=False,
    )
    op.create_table(
        "goal_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_goal_projection_last_updated", "goal_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_goal_projection_lifecycle_status", "goal_projection", ["lifecycle_status"], unique=False
    )
    op.create_index(
        "ix_goal_projection_start_date", "goal_projection", ["start_date"], unique=False
    )
    op.create_index(
        "ix_goal_projection_subject", "goal_projection", ["subject_reference"], unique=False
    )
    op.create_table(
        "imagingstudy_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("encounter_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_imagingstudy_projection_encounter",
        "imagingstudy_projection",
        ["encounter_reference"],
        unique=False,
    )
    op.create_index(
        "ix_imagingstudy_projection_last_updated",
        "imagingstudy_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_imagingstudy_projection_started_at",
        "imagingstudy_projection",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        "ix_imagingstudy_projection_status", "imagingstudy_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_imagingstudy_projection_subject",
        "imagingstudy_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_table(
        "immunization_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("vaccine_code", sa.String(length=64), nullable=True),
        sa.Column("occurrence_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_immunization_projection_last_updated",
        "immunization_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_immunization_projection_occurrence_at",
        "immunization_projection",
        ["occurrence_at"],
        unique=False,
    )
    op.create_index(
        "ix_immunization_projection_patient",
        "immunization_projection",
        ["patient_reference"],
        unique=False,
    )
    op.create_index(
        "ix_immunization_projection_status", "immunization_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_immunization_projection_vaccine_code",
        "immunization_projection",
        ["vaccine_code"],
        unique=False,
    )
    op.create_table(
        "location_projection",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("type_code", sa.String(length=64), nullable=True),
        sa.Column("organization_reference", sa.String(length=128), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_location_projection_last_updated", "location_projection", ["last_updated"], unique=False
    )
    op.create_index("ix_location_projection_name", "location_projection", ["name"], unique=False)
    op.create_index(
        "ix_location_projection_organization",
        "location_projection",
        ["organization_reference"],
        unique=False,
    )
    op.create_index(
        "ix_location_projection_status", "location_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_location_projection_type", "location_projection", ["type_code"], unique=False
    )
    op.create_table(
        "medication_projection",
        sa.Column("code_code", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_medication_projection_code", "medication_projection", ["code_code"], unique=False
    )
    op.create_index(
        "ix_medication_projection_last_updated",
        "medication_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_medication_projection_status", "medication_projection", ["status"], unique=False
    )
    op.create_table(
        "medicationadministration_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("encounter_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("occurrence_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_medicationadministration_projection_encounter",
        "medicationadministration_projection",
        ["encounter_reference"],
        unique=False,
    )
    op.create_index(
        "ix_medicationadministration_projection_last_updated",
        "medicationadministration_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_medicationadministration_projection_occurrence_at",
        "medicationadministration_projection",
        ["occurrence_at"],
        unique=False,
    )
    op.create_index(
        "ix_medicationadministration_projection_status",
        "medicationadministration_projection",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_medicationadministration_projection_subject",
        "medicationadministration_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_table(
        "medicationdispense_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("when_handed_over", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_medicationdispense_projection_last_updated",
        "medicationdispense_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_medicationdispense_projection_status",
        "medicationdispense_projection",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_medicationdispense_projection_subject",
        "medicationdispense_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_index(
        "ix_medicationdispense_projection_when_handed_over",
        "medicationdispense_projection",
        ["when_handed_over"],
        unique=False,
    )
    op.create_table(
        "medicationstatement_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_medicationstatement_projection_effective_at",
        "medicationstatement_projection",
        ["effective_at"],
        unique=False,
    )
    op.create_index(
        "ix_medicationstatement_projection_last_updated",
        "medicationstatement_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_medicationstatement_projection_status",
        "medicationstatement_projection",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_medicationstatement_projection_subject",
        "medicationstatement_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_table(
        "nutritionorder_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("encounter_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_nutritionorder_projection_encounter",
        "nutritionorder_projection",
        ["encounter_reference"],
        unique=False,
    )
    op.create_index(
        "ix_nutritionorder_projection_last_updated",
        "nutritionorder_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_nutritionorder_projection_patient",
        "nutritionorder_projection",
        ["patient_reference"],
        unique=False,
    )
    op.create_index(
        "ix_nutritionorder_projection_status", "nutritionorder_projection", ["status"], unique=False
    )
    op.create_table(
        "practitionerrole_projection",
        sa.Column("practitioner_reference", sa.String(length=128), nullable=True),
        sa.Column("organization_reference", sa.String(length=128), nullable=True),
        sa.Column("role_code", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_practitionerrole_projection_active",
        "practitionerrole_projection",
        ["active"],
        unique=False,
    )
    op.create_index(
        "ix_practitionerrole_projection_last_updated",
        "practitionerrole_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_practitionerrole_projection_organization",
        "practitionerrole_projection",
        ["organization_reference"],
        unique=False,
    )
    op.create_index(
        "ix_practitionerrole_projection_practitioner",
        "practitionerrole_projection",
        ["practitioner_reference"],
        unique=False,
    )
    op.create_index(
        "ix_practitionerrole_projection_role",
        "practitionerrole_projection",
        ["role_code"],
        unique=False,
    )
    op.create_table(
        "relatedperson_projection",
        sa.Column("patient_reference", sa.String(length=128), nullable=True),
        sa.Column("family", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_relatedperson_projection_active", "relatedperson_projection", ["active"], unique=False
    )
    op.create_index(
        "ix_relatedperson_projection_family", "relatedperson_projection", ["family"], unique=False
    )
    op.create_index(
        "ix_relatedperson_projection_last_updated",
        "relatedperson_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_relatedperson_projection_patient",
        "relatedperson_projection",
        ["patient_reference"],
        unique=False,
    )
    op.create_table(
        "schedule_projection",
        sa.Column("actor_reference", sa.String(length=128), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_schedule_projection_active", "schedule_projection", ["active"], unique=False
    )
    op.create_index(
        "ix_schedule_projection_actor", "schedule_projection", ["actor_reference"], unique=False
    )
    op.create_index(
        "ix_schedule_projection_last_updated", "schedule_projection", ["last_updated"], unique=False
    )
    op.create_table(
        "servicerequest_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("encounter_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("authored_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_servicerequest_projection_authored_on",
        "servicerequest_projection",
        ["authored_on"],
        unique=False,
    )
    op.create_index(
        "ix_servicerequest_projection_encounter",
        "servicerequest_projection",
        ["encounter_reference"],
        unique=False,
    )
    op.create_index(
        "ix_servicerequest_projection_last_updated",
        "servicerequest_projection",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        "ix_servicerequest_projection_status", "servicerequest_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_servicerequest_projection_subject",
        "servicerequest_projection",
        ["subject_reference"],
        unique=False,
    )
    op.create_table(
        "slot_projection",
        sa.Column("schedule_reference", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_slot_projection_last_updated", "slot_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_slot_projection_schedule", "slot_projection", ["schedule_reference"], unique=False
    )
    op.create_index("ix_slot_projection_start_at", "slot_projection", ["start_at"], unique=False)
    op.create_index("ix_slot_projection_status", "slot_projection", ["status"], unique=False)
    op.create_table(
        "specimen_projection",
        sa.Column("subject_reference", sa.String(length=128), nullable=True),
        sa.Column("type_code", sa.String(length=64), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_specimen_projection_collected_at", "specimen_projection", ["collected_at"], unique=False
    )
    op.create_index(
        "ix_specimen_projection_last_updated", "specimen_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_specimen_projection_status", "specimen_projection", ["status"], unique=False
    )
    op.create_index(
        "ix_specimen_projection_subject", "specimen_projection", ["subject_reference"], unique=False
    )
    op.create_index(
        "ix_specimen_projection_type", "specimen_projection", ["type_code"], unique=False
    )
    op.create_table(
        "task_projection",
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("intent", sa.String(length=32), nullable=True),
        sa.Column("authored_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_reference", sa.String(length=128), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_index(
        "ix_task_projection_authored_on", "task_projection", ["authored_on"], unique=False
    )
    op.create_index("ix_task_projection_intent", "task_projection", ["intent"], unique=False)
    op.create_index(
        "ix_task_projection_last_updated", "task_projection", ["last_updated"], unique=False
    )
    op.create_index(
        "ix_task_projection_owner", "task_projection", ["owner_reference"], unique=False
    )
    op.create_index("ix_task_projection_status", "task_projection", ["status"], unique=False)
    op.create_index(
        "ix_resource_versions_content_gin",
        "resource_versions",
        ["content"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_index(
        "ix_resource_versions_content_gin", table_name="resource_versions", postgresql_using="gin"
    )
    op.drop_index("ix_task_projection_status", table_name="task_projection")
    op.drop_index("ix_task_projection_owner", table_name="task_projection")
    op.drop_index("ix_task_projection_last_updated", table_name="task_projection")
    op.drop_index("ix_task_projection_intent", table_name="task_projection")
    op.drop_index("ix_task_projection_authored_on", table_name="task_projection")
    op.drop_table("task_projection")
    op.drop_index("ix_specimen_projection_type", table_name="specimen_projection")
    op.drop_index("ix_specimen_projection_subject", table_name="specimen_projection")
    op.drop_index("ix_specimen_projection_status", table_name="specimen_projection")
    op.drop_index("ix_specimen_projection_last_updated", table_name="specimen_projection")
    op.drop_index("ix_specimen_projection_collected_at", table_name="specimen_projection")
    op.drop_table("specimen_projection")
    op.drop_index("ix_slot_projection_status", table_name="slot_projection")
    op.drop_index("ix_slot_projection_start_at", table_name="slot_projection")
    op.drop_index("ix_slot_projection_schedule", table_name="slot_projection")
    op.drop_index("ix_slot_projection_last_updated", table_name="slot_projection")
    op.drop_table("slot_projection")
    op.drop_index("ix_servicerequest_projection_subject", table_name="servicerequest_projection")
    op.drop_index("ix_servicerequest_projection_status", table_name="servicerequest_projection")
    op.drop_index(
        "ix_servicerequest_projection_last_updated", table_name="servicerequest_projection"
    )
    op.drop_index("ix_servicerequest_projection_encounter", table_name="servicerequest_projection")
    op.drop_index(
        "ix_servicerequest_projection_authored_on", table_name="servicerequest_projection"
    )
    op.drop_table("servicerequest_projection")
    op.drop_index("ix_schedule_projection_last_updated", table_name="schedule_projection")
    op.drop_index("ix_schedule_projection_actor", table_name="schedule_projection")
    op.drop_index("ix_schedule_projection_active", table_name="schedule_projection")
    op.drop_table("schedule_projection")
    op.drop_index("ix_relatedperson_projection_patient", table_name="relatedperson_projection")
    op.drop_index("ix_relatedperson_projection_last_updated", table_name="relatedperson_projection")
    op.drop_index("ix_relatedperson_projection_family", table_name="relatedperson_projection")
    op.drop_index("ix_relatedperson_projection_active", table_name="relatedperson_projection")
    op.drop_table("relatedperson_projection")
    op.drop_index("ix_practitionerrole_projection_role", table_name="practitionerrole_projection")
    op.drop_index(
        "ix_practitionerrole_projection_practitioner", table_name="practitionerrole_projection"
    )
    op.drop_index(
        "ix_practitionerrole_projection_organization", table_name="practitionerrole_projection"
    )
    op.drop_index(
        "ix_practitionerrole_projection_last_updated", table_name="practitionerrole_projection"
    )
    op.drop_index("ix_practitionerrole_projection_active", table_name="practitionerrole_projection")
    op.drop_table("practitionerrole_projection")
    op.drop_index("ix_nutritionorder_projection_status", table_name="nutritionorder_projection")
    op.drop_index("ix_nutritionorder_projection_patient", table_name="nutritionorder_projection")
    op.drop_index(
        "ix_nutritionorder_projection_last_updated", table_name="nutritionorder_projection"
    )
    op.drop_index("ix_nutritionorder_projection_encounter", table_name="nutritionorder_projection")
    op.drop_table("nutritionorder_projection")
    op.drop_index(
        "ix_medicationstatement_projection_subject", table_name="medicationstatement_projection"
    )
    op.drop_index(
        "ix_medicationstatement_projection_status", table_name="medicationstatement_projection"
    )
    op.drop_index(
        "ix_medicationstatement_projection_last_updated",
        table_name="medicationstatement_projection",
    )
    op.drop_index(
        "ix_medicationstatement_projection_effective_at",
        table_name="medicationstatement_projection",
    )
    op.drop_table("medicationstatement_projection")
    op.drop_index(
        "ix_medicationdispense_projection_when_handed_over",
        table_name="medicationdispense_projection",
    )
    op.drop_index(
        "ix_medicationdispense_projection_subject", table_name="medicationdispense_projection"
    )
    op.drop_index(
        "ix_medicationdispense_projection_status", table_name="medicationdispense_projection"
    )
    op.drop_index(
        "ix_medicationdispense_projection_last_updated", table_name="medicationdispense_projection"
    )
    op.drop_table("medicationdispense_projection")
    op.drop_index(
        "ix_medicationadministration_projection_subject",
        table_name="medicationadministration_projection",
    )
    op.drop_index(
        "ix_medicationadministration_projection_status",
        table_name="medicationadministration_projection",
    )
    op.drop_index(
        "ix_medicationadministration_projection_occurrence_at",
        table_name="medicationadministration_projection",
    )
    op.drop_index(
        "ix_medicationadministration_projection_last_updated",
        table_name="medicationadministration_projection",
    )
    op.drop_index(
        "ix_medicationadministration_projection_encounter",
        table_name="medicationadministration_projection",
    )
    op.drop_table("medicationadministration_projection")
    op.drop_index("ix_medication_projection_status", table_name="medication_projection")
    op.drop_index("ix_medication_projection_last_updated", table_name="medication_projection")
    op.drop_index("ix_medication_projection_code", table_name="medication_projection")
    op.drop_table("medication_projection")
    op.drop_index("ix_location_projection_type", table_name="location_projection")
    op.drop_index("ix_location_projection_status", table_name="location_projection")
    op.drop_index("ix_location_projection_organization", table_name="location_projection")
    op.drop_index("ix_location_projection_name", table_name="location_projection")
    op.drop_index("ix_location_projection_last_updated", table_name="location_projection")
    op.drop_table("location_projection")
    op.drop_index("ix_immunization_projection_vaccine_code", table_name="immunization_projection")
    op.drop_index("ix_immunization_projection_status", table_name="immunization_projection")
    op.drop_index("ix_immunization_projection_patient", table_name="immunization_projection")
    op.drop_index("ix_immunization_projection_occurrence_at", table_name="immunization_projection")
    op.drop_index("ix_immunization_projection_last_updated", table_name="immunization_projection")
    op.drop_table("immunization_projection")
    op.drop_index("ix_imagingstudy_projection_subject", table_name="imagingstudy_projection")
    op.drop_index("ix_imagingstudy_projection_status", table_name="imagingstudy_projection")
    op.drop_index("ix_imagingstudy_projection_started_at", table_name="imagingstudy_projection")
    op.drop_index("ix_imagingstudy_projection_last_updated", table_name="imagingstudy_projection")
    op.drop_index("ix_imagingstudy_projection_encounter", table_name="imagingstudy_projection")
    op.drop_table("imagingstudy_projection")
    op.drop_index("ix_goal_projection_subject", table_name="goal_projection")
    op.drop_index("ix_goal_projection_start_date", table_name="goal_projection")
    op.drop_index("ix_goal_projection_lifecycle_status", table_name="goal_projection")
    op.drop_index("ix_goal_projection_last_updated", table_name="goal_projection")
    op.drop_table("goal_projection")
    op.drop_index(
        "ix_familymemberhistory_projection_status", table_name="familymemberhistory_projection"
    )
    op.drop_index(
        "ix_familymemberhistory_projection_relationship",
        table_name="familymemberhistory_projection",
    )
    op.drop_index(
        "ix_familymemberhistory_projection_patient", table_name="familymemberhistory_projection"
    )
    op.drop_index(
        "ix_familymemberhistory_projection_last_updated",
        table_name="familymemberhistory_projection",
    )
    op.drop_table("familymemberhistory_projection")
    op.drop_index("ix_episodeofcare_projection_status", table_name="episodeofcare_projection")
    op.drop_index("ix_episodeofcare_projection_period_start", table_name="episodeofcare_projection")
    op.drop_index("ix_episodeofcare_projection_patient", table_name="episodeofcare_projection")
    op.drop_index("ix_episodeofcare_projection_last_updated", table_name="episodeofcare_projection")
    op.drop_table("episodeofcare_projection")
    op.drop_index("ix_documentreference_projection_type", table_name="documentreference_projection")
    op.drop_index(
        "ix_documentreference_projection_subject", table_name="documentreference_projection"
    )
    op.drop_index(
        "ix_documentreference_projection_status", table_name="documentreference_projection"
    )
    op.drop_index(
        "ix_documentreference_projection_last_updated", table_name="documentreference_projection"
    )
    op.drop_index(
        "ix_documentreference_projection_doc_status", table_name="documentreference_projection"
    )
    op.drop_index(
        "ix_documentreference_projection_doc_date", table_name="documentreference_projection"
    )
    op.drop_table("documentreference_projection")
    op.drop_index("ix_coverage_projection_status", table_name="coverage_projection")
    op.drop_index("ix_coverage_projection_last_updated", table_name="coverage_projection")
    op.drop_index("ix_coverage_projection_beneficiary", table_name="coverage_projection")
    op.drop_table("coverage_projection")
    op.drop_index("ix_composition_projection_type", table_name="composition_projection")
    op.drop_index("ix_composition_projection_subject", table_name="composition_projection")
    op.drop_index("ix_composition_projection_status", table_name="composition_projection")
    op.drop_index("ix_composition_projection_last_updated", table_name="composition_projection")
    op.drop_index("ix_composition_projection_encounter", table_name="composition_projection")
    op.drop_index("ix_composition_projection_doc_date", table_name="composition_projection")
    op.drop_table("composition_projection")
    op.drop_index(
        "ix_communicationrequest_projection_subject", table_name="communicationrequest_projection"
    )
    op.drop_index(
        "ix_communicationrequest_projection_status", table_name="communicationrequest_projection"
    )
    op.drop_index(
        "ix_communicationrequest_projection_last_updated",
        table_name="communicationrequest_projection",
    )
    op.drop_index(
        "ix_communicationrequest_projection_authored_on",
        table_name="communicationrequest_projection",
    )
    op.drop_table("communicationrequest_projection")
    op.drop_index("ix_communication_projection_subject", table_name="communication_projection")
    op.drop_index("ix_communication_projection_status", table_name="communication_projection")
    op.drop_index("ix_communication_projection_sent_at", table_name="communication_projection")
    op.drop_index("ix_communication_projection_last_updated", table_name="communication_projection")
    op.drop_table("communication_projection")
    op.drop_index("ix_claim_projection_status", table_name="claim_projection")
    op.drop_index("ix_claim_projection_patient", table_name="claim_projection")
    op.drop_index("ix_claim_projection_last_updated", table_name="claim_projection")
    op.drop_index("ix_claim_projection_created_at", table_name="claim_projection")
    op.drop_table("claim_projection")
    op.drop_index("ix_careplan_projection_subject", table_name="careplan_projection")
    op.drop_index("ix_careplan_projection_status", table_name="careplan_projection")
    op.drop_index("ix_careplan_projection_last_updated", table_name="careplan_projection")
    op.drop_index("ix_careplan_projection_encounter", table_name="careplan_projection")
    op.drop_table("careplan_projection")
    op.drop_index("ix_appointment_projection_status", table_name="appointment_projection")
    op.drop_index("ix_appointment_projection_start_at", table_name="appointment_projection")
    op.drop_index("ix_appointment_projection_patient", table_name="appointment_projection")
    op.drop_index("ix_appointment_projection_last_updated", table_name="appointment_projection")
    op.drop_table("appointment_projection")
    # ### end Alembic commands ###
