"""initial

Revision ID: 59aeae159300
Revises:
Create Date: 2026-05-27 00:15:30.825469

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59aeae159300'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergyintolerance_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_ref', sa.String(length=128), nullable=True),
    sa.Column('code_code', sa.String(length=64), nullable=True),
    sa.Column('clinical_status', sa.String(length=32), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_allergyintolerance_index_clinical_status', 'allergyintolerance_index', ['clinical_status'], unique=False)
    op.create_index('ix_allergyintolerance_index_code', 'allergyintolerance_index', ['code_code'], unique=False)
    op.create_index('ix_allergyintolerance_index_criticality', 'allergyintolerance_index', ['criticality'], unique=False)
    op.create_index('ix_allergyintolerance_index_last_updated', 'allergyintolerance_index', ['last_updated'], unique=False)
    op.create_index('ix_allergyintolerance_index_patient', 'allergyintolerance_index', ['patient_ref'], unique=False)
    op.create_table('condition_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('encounter_ref', sa.String(length=128), nullable=True),
    sa.Column('clinical_status', sa.String(length=32), nullable=True),
    sa.Column('code_code', sa.String(length=64), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_condition_index_clinical_status', 'condition_index', ['clinical_status'], unique=False)
    op.create_index('ix_condition_index_code', 'condition_index', ['code_code'], unique=False)
    op.create_index('ix_condition_index_encounter', 'condition_index', ['encounter_ref'], unique=False)
    op.create_index('ix_condition_index_last_updated', 'condition_index', ['last_updated'], unique=False)
    op.create_index('ix_condition_index_recorded_date', 'condition_index', ['recorded_date'], unique=False)
    op.create_index('ix_condition_index_subject', 'condition_index', ['subject_ref'], unique=False)
    op.create_table('diagnosticreport_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('encounter_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('code_code', sa.String(length=64), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_diagnosticreport_index_code', 'diagnosticreport_index', ['code_code'], unique=False)
    op.create_index('ix_diagnosticreport_index_effective_at', 'diagnosticreport_index', ['effective_at'], unique=False)
    op.create_index('ix_diagnosticreport_index_encounter', 'diagnosticreport_index', ['encounter_ref'], unique=False)
    op.create_index('ix_diagnosticreport_index_last_updated', 'diagnosticreport_index', ['last_updated'], unique=False)
    op.create_index('ix_diagnosticreport_index_status', 'diagnosticreport_index', ['status'], unique=False)
    op.create_index('ix_diagnosticreport_index_subject', 'diagnosticreport_index', ['subject_ref'], unique=False)
    op.create_table('encounter_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('class_code', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_encounter_index_class', 'encounter_index', ['class_code'], unique=False)
    op.create_index('ix_encounter_index_last_updated', 'encounter_index', ['last_updated'], unique=False)
    op.create_index('ix_encounter_index_period_end', 'encounter_index', ['period_end'], unique=False)
    op.create_index('ix_encounter_index_period_start', 'encounter_index', ['period_start'], unique=False)
    op.create_index('ix_encounter_index_status', 'encounter_index', ['status'], unique=False)
    op.create_index('ix_encounter_index_subject', 'encounter_index', ['subject_ref'], unique=False)
    op.create_table('medicationrequest_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('authored_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requester_ref', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_medicationrequest_index_authored_on', 'medicationrequest_index', ['authored_on'], unique=False)
    op.create_index('ix_medicationrequest_index_intent', 'medicationrequest_index', ['intent'], unique=False)
    op.create_index('ix_medicationrequest_index_last_updated', 'medicationrequest_index', ['last_updated'], unique=False)
    op.create_index('ix_medicationrequest_index_requester', 'medicationrequest_index', ['requester_ref'], unique=False)
    op.create_index('ix_medicationrequest_index_status', 'medicationrequest_index', ['status'], unique=False)
    op.create_index('ix_medicationrequest_index_subject', 'medicationrequest_index', ['subject_ref'], unique=False)
    op.create_table('observation_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('encounter_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('code_system', sa.String(length=255), nullable=True),
    sa.Column('code_code', sa.String(length=64), nullable=True),
    sa.Column('category_code', sa.String(length=64), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_quantity_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('value_quantity_unit', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_observation_index_category', 'observation_index', ['category_code'], unique=False)
    op.create_index('ix_observation_index_code', 'observation_index', ['code_code'], unique=False)
    op.create_index('ix_observation_index_effective_at', 'observation_index', ['effective_at'], unique=False)
    op.create_index('ix_observation_index_encounter', 'observation_index', ['encounter_ref'], unique=False)
    op.create_index('ix_observation_index_last_updated', 'observation_index', ['last_updated'], unique=False)
    op.create_index('ix_observation_index_status', 'observation_index', ['status'], unique=False)
    op.create_index('ix_observation_index_subject_code', 'observation_index', ['subject_ref', 'code_code'], unique=False)
    op.create_index('ix_observation_index_subject_effective', 'observation_index', ['subject_ref', 'effective_at'], unique=False)
    op.create_index('ix_observation_index_value_quantity', 'observation_index', ['value_quantity_value'], unique=False)
    op.create_table('organization_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('type_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_organization_index_active', 'organization_index', ['active'], unique=False)
    op.create_index('ix_organization_index_last_updated', 'organization_index', ['last_updated'], unique=False)
    op.create_index('ix_organization_index_name', 'organization_index', ['name'], unique=False)
    op.create_index('ix_organization_index_type', 'organization_index', ['type_code'], unique=False)
    op.create_table('patient_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('given', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_patient_index_active', 'patient_index', ['active'], unique=False)
    op.create_index('ix_patient_index_birth_date', 'patient_index', ['birth_date'], unique=False)
    op.create_index('ix_patient_index_family', 'patient_index', ['family'], unique=False)
    op.create_index('ix_patient_index_gender', 'patient_index', ['gender'], unique=False)
    op.create_index('ix_patient_index_given', 'patient_index', ['given'], unique=False)
    op.create_index('ix_patient_index_last_updated', 'patient_index', ['last_updated'], unique=False)
    op.create_table('practitioner_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('given', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_practitioner_index_active', 'practitioner_index', ['active'], unique=False)
    op.create_index('ix_practitioner_index_family', 'practitioner_index', ['family'], unique=False)
    op.create_index('ix_practitioner_index_given', 'practitioner_index', ['given'], unique=False)
    op.create_index('ix_practitioner_index_last_updated', 'practitioner_index', ['last_updated'], unique=False)
    op.create_table('procedure_index',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('encounter_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('code_code', sa.String(length=64), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('ix_procedure_index_code', 'procedure_index', ['code_code'], unique=False)
    op.create_index('ix_procedure_index_encounter', 'procedure_index', ['encounter_ref'], unique=False)
    op.create_index('ix_procedure_index_last_updated', 'procedure_index', ['last_updated'], unique=False)
    op.create_index('ix_procedure_index_performed_at', 'procedure_index', ['performed_at'], unique=False)
    op.create_index('ix_procedure_index_status', 'procedure_index', ['status'], unique=False)
    op.create_index('ix_procedure_index_subject', 'procedure_index', ['subject_ref'], unique=False)
    op.create_table('resource_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'version_id', name='uq_resource_versions_type_id_version')
    )
    op.create_index(op.f('ix_resource_versions_last_updated'), 'resource_versions', ['last_updated'], unique=False)
    op.create_index(op.f('ix_resource_versions_resource_id'), 'resource_versions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_versions_resource_type'), 'resource_versions', ['resource_type'], unique=False)
    op.create_index('ix_resource_versions_type_id', 'resource_versions', ['resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_versions_type_id', table_name='resource_versions')
    op.drop_index(op.f('ix_resource_versions_resource_type'), table_name='resource_versions')
    op.drop_index(op.f('ix_resource_versions_resource_id'), table_name='resource_versions')
    op.drop_index(op.f('ix_resource_versions_last_updated'), table_name='resource_versions')
    op.drop_table('resource_versions')
    op.drop_index('ix_procedure_index_subject', table_name='procedure_index')
    op.drop_index('ix_procedure_index_status', table_name='procedure_index')
    op.drop_index('ix_procedure_index_performed_at', table_name='procedure_index')
    op.drop_index('ix_procedure_index_last_updated', table_name='procedure_index')
    op.drop_index('ix_procedure_index_encounter', table_name='procedure_index')
    op.drop_index('ix_procedure_index_code', table_name='procedure_index')
    op.drop_table('procedure_index')
    op.drop_index('ix_practitioner_index_last_updated', table_name='practitioner_index')
    op.drop_index('ix_practitioner_index_given', table_name='practitioner_index')
    op.drop_index('ix_practitioner_index_family', table_name='practitioner_index')
    op.drop_index('ix_practitioner_index_active', table_name='practitioner_index')
    op.drop_table('practitioner_index')
    op.drop_index('ix_patient_index_last_updated', table_name='patient_index')
    op.drop_index('ix_patient_index_given', table_name='patient_index')
    op.drop_index('ix_patient_index_gender', table_name='patient_index')
    op.drop_index('ix_patient_index_family', table_name='patient_index')
    op.drop_index('ix_patient_index_birth_date', table_name='patient_index')
    op.drop_index('ix_patient_index_active', table_name='patient_index')
    op.drop_table('patient_index')
    op.drop_index('ix_organization_index_type', table_name='organization_index')
    op.drop_index('ix_organization_index_name', table_name='organization_index')
    op.drop_index('ix_organization_index_last_updated', table_name='organization_index')
    op.drop_index('ix_organization_index_active', table_name='organization_index')
    op.drop_table('organization_index')
    op.drop_index('ix_observation_index_value_quantity', table_name='observation_index')
    op.drop_index('ix_observation_index_subject_effective', table_name='observation_index')
    op.drop_index('ix_observation_index_subject_code', table_name='observation_index')
    op.drop_index('ix_observation_index_status', table_name='observation_index')
    op.drop_index('ix_observation_index_last_updated', table_name='observation_index')
    op.drop_index('ix_observation_index_encounter', table_name='observation_index')
    op.drop_index('ix_observation_index_effective_at', table_name='observation_index')
    op.drop_index('ix_observation_index_code', table_name='observation_index')
    op.drop_index('ix_observation_index_category', table_name='observation_index')
    op.drop_table('observation_index')
    op.drop_index('ix_medicationrequest_index_subject', table_name='medicationrequest_index')
    op.drop_index('ix_medicationrequest_index_status', table_name='medicationrequest_index')
    op.drop_index('ix_medicationrequest_index_requester', table_name='medicationrequest_index')
    op.drop_index('ix_medicationrequest_index_last_updated', table_name='medicationrequest_index')
    op.drop_index('ix_medicationrequest_index_intent', table_name='medicationrequest_index')
    op.drop_index('ix_medicationrequest_index_authored_on', table_name='medicationrequest_index')
    op.drop_table('medicationrequest_index')
    op.drop_index('ix_encounter_index_subject', table_name='encounter_index')
    op.drop_index('ix_encounter_index_status', table_name='encounter_index')
    op.drop_index('ix_encounter_index_period_start', table_name='encounter_index')
    op.drop_index('ix_encounter_index_period_end', table_name='encounter_index')
    op.drop_index('ix_encounter_index_last_updated', table_name='encounter_index')
    op.drop_index('ix_encounter_index_class', table_name='encounter_index')
    op.drop_table('encounter_index')
    op.drop_index('ix_diagnosticreport_index_subject', table_name='diagnosticreport_index')
    op.drop_index('ix_diagnosticreport_index_status', table_name='diagnosticreport_index')
    op.drop_index('ix_diagnosticreport_index_last_updated', table_name='diagnosticreport_index')
    op.drop_index('ix_diagnosticreport_index_encounter', table_name='diagnosticreport_index')
    op.drop_index('ix_diagnosticreport_index_effective_at', table_name='diagnosticreport_index')
    op.drop_index('ix_diagnosticreport_index_code', table_name='diagnosticreport_index')
    op.drop_table('diagnosticreport_index')
    op.drop_index('ix_condition_index_subject', table_name='condition_index')
    op.drop_index('ix_condition_index_recorded_date', table_name='condition_index')
    op.drop_index('ix_condition_index_last_updated', table_name='condition_index')
    op.drop_index('ix_condition_index_encounter', table_name='condition_index')
    op.drop_index('ix_condition_index_code', table_name='condition_index')
    op.drop_index('ix_condition_index_clinical_status', table_name='condition_index')
    op.drop_table('condition_index')
    op.drop_index('ix_allergyintolerance_index_patient', table_name='allergyintolerance_index')
    op.drop_index('ix_allergyintolerance_index_last_updated', table_name='allergyintolerance_index')
    op.drop_index('ix_allergyintolerance_index_criticality', table_name='allergyintolerance_index')
    op.drop_index('ix_allergyintolerance_index_code', table_name='allergyintolerance_index')
    op.drop_index('ix_allergyintolerance_index_clinical_status', table_name='allergyintolerance_index')
    op.drop_table('allergyintolerance_index')
    # ### end Alembic commands ###
